# Generated by Django 4.1.10 on 2023-09-22 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
